### PR TITLE
Fix that the app crashes by trying to input a number into a cell

### PR DESCRIPTION
**Pull request by ryonakano**
## Actual Behavior

peek 2018-09-06 12-36

The app crashes by trying to input a number into a cell.

## Changes Summary

* Fix that the app crashes by trying to input a number into a cell
* Fix that redo is not work

### CODE REVIEW

**Comment by BaptisteGelez** [comment]
Thanks for your contribution. I don't have time nor will to maintain this app anymore, would you like me to transfer you the ownership?

**Comment by ryonakano** [comment]
Yes, I would be glad to. But I have only a little knowledge of Vala and still studying it. So, would it be possible for you to remain as a member of administrators after transferred?

**Comment by BaptisteGelez** [comment]
Thank you very much! I'm happy to see this project having a new maintainer, I was a bit disappointed not to have the time to continue it. And yes, it will be possible for me to remain as an administrator, you'll just have to give me write access from the repo settings once it'll be yours. And if you have any question with Vala, I'm here to help (even if may not be completely mastering it too).

**Comment by ryonakano** [comment]
I've transferred! And you (and SkyzohKey) remain as admins.
Thank you for transferring this repo and giving me a chance to maintain this app. I'm going to learn Vala more and do my best in this app! :muscle:

**Pull request merged**
